# --- Configurações do Banco de Dados PostgreSQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/controle_estoque_db
spring.datasource.username=postgres
spring.datasource.password=246819

# --- Configurações do Hibernate ---
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# --- Configurações de Segurança ---
api.security.token.secret=minha-chave-secreta-super-longa-e-dificil-de-adivinhar-12345

# --- Configurações do Spring Web (IMPORTANTE!) ---
# Define que apenas /static/** são recursos estáticos
spring.web.resources.static-locations=classpath:/static/
spring.web.resources.static-path-pattern=/static/**

# Desabilita o mapeamento padrão de recursos estáticos para /
spring.mvc.static-path-pattern=/static/**

# Define o contexto raiz da aplicação
server.servlet.context-path=/

# --- CORS---
# Permite requisições do frontend
spring.web.cors.allowed-origins=http://localhost:3000,http://localhost:5173
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true
